# -*- mode: ruby -*-
# vi: set ft=ruby :

$vm_ip = "192.168.5.100"
$vm_memory = 1024

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.7"

  # Make exam simplify
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.check_guest_additions = false
    v.functional_vboxsf     = false
    v.memory = $vm_memory
  end

  ## Port forwarding for Web app
  config.vm.network :forwarded_port, guest: 8080, host: 5001
  config.vm.network :private_network, ip: $vm_ip

  config.vm.synced_folder "./app", "/var/www/html", :type => "nfs"
end
