# -*- mode: ruby -*-
# vi: set ft=ruby :

$vm_ip = "192.168.5.100"
$vm_memory = 1024

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-6.7"

  # Make exam simplify
  config.vm.box_check_update = false
  config.vbguest.auto_update = false

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.memory = $vm_memory
  end

  ## Port forwarding for Web app
  config.vm.network :forwarded_port, guest: 8080, host: 5001
  config.vm.network :private_network, ip: $vm_ip

  config.vm.synced_folder "./app", "/var/app", :type => "nfs"
  config.vm.synced_folder "./docker", "/var/docker", :type => "nfs"

  config.vm.provision :shell, path: "scripts/provision.sh"
  config.vm.provision :shell, path: "scripts/run.sh", run: "always"

end
